import "./components/custom-select.js";
import "./components/overlay.js";
import "./components/slider.js";
import "./components/asideMenu.js";
import "./components/accordeon.js";
import "./components/map.js";
import "./components/menu/mobileMenu.js";
import "./components/menu/menuTechnic.js";
import "./components/menu/menuSearch.js";
